### ISSUE TITLE
Create new python file to store the encoded data

### ISSUE THREAD

**Issue by MVenkata-Rathnam** [NJACKWinterOfCode/Fake-News-Detector#12]
To bring in modularity, we can create a separate python file to find and store the encoded news and titles data and the existing fake.py file can be used only for importing the encoded data and training the model.

**Comment by MVenkata-Rathnam** [comment]
Can I go ahead and work on this issue?

**Comment by piyushmishra12** [comment]
Sure!

**Comment by MVenkata-Rathnam** [comment]
May I close this issue?

**Comment by piyushmishra12** [comment]
Yeah!
