### ISSUE TITLE
Employ LSTM model for remembering text 

### ISSUE THREAD

**Issue by piyushmishra12** [NJACKWinterOfCode/Fake-News-Detector#4]

**Comment by MVenkata-Rathnam** [comment]
I wish to work on this issue.  Can I go ahead?

**Comment by piyushmishra12** [comment]
Sure! Go ahead.

**Comment by MVenkata-Rathnam** [comment]
shall I create a separate file for LSTM model or should I modify the fake.py?

**Comment by piyushmishra12** [comment]
Yeah it'd be easier if you make a separate file.

**Comment by MVenkata-Rathnam** [comment]
LSTM has to be built for remembering previous news instances right.  But it will be more intuitive to be a word level LSTM.

**Comment by piyushmishra12** [comment]
I was going for a word level LSTM since 2 news articles wouldn't be related.

**Comment by MVenkata-Rathnam** [comment]
I feel that the current encoding may not suit LSTM.  The dimension of each news is over 10000 and for each word, just a single real value is used.  We have to first do an efficient encoding before trying with LSTM.  Am I right?  Could you provide me any suggestions on this?

**Comment by piyushmishra12** [comment]
I was thinking that we should remember only a specific number of words, say 40, prior to the current word. So whenever a word is incremented, the data structure would remove the first word, index of rest of the words will be reduced by one, and the latest word will be added at the end.
So iteration would start from the 40th word and go on till the end but the size of the data structure would remain 40. Makes sense?

**Comment by MVenkata-Rathnam** [comment]
Yes, it makes absolute sense.

**Comment by piyushmishra12** [comment]
Hey check [this](https://medium.com/@sabber/classifying-yelp-review-comments-using-lstm-and-word-embeddings-part-1-eb2275e4066b) out. Might be of some help!

**Comment by MVenkata-Rathnam** [comment]
Embedding(15000, 1, input_length=10623)
LSTM(units=256)

or

LSTM(units = 256, input_shape=(10623,1))

Both of these definitions consumes very much time to train.  Here each news instance is padded to the maximum 10623 and each word is represented by a single real value.  I think the length 10623 is the reason.

**Comment by piyushmishra12** [comment]
If you think size is a problem, just make a pull request regardless (a different python file) and I'll merge it because conceptually its fine. Then you could raise another issue for size and feature select using CNN and max-pooling?

**Comment by MVenkata-Rathnam** [comment]
Ok :)

**Comment by MVenkata-Rathnam** [comment]
Can we open a new issue to improve the LSTM model?

**Comment by piyushmishra12** [comment]
Sure go ahead. Please make sure to specify the improvements you wish to make in the issue itself.
